# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "The tesseract release version to build; e.g. '5.5.1'"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/tesseract-ocr/tesseract/blob/main/.github/workflows/autotools-openmp.yml
      - name: Get source code
        uses: actions/checkout@v4
        with:
          repository: tesseract-ocr/tesseract
          ref: ${{ inputs.version }}
          fetch-depth: 1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            libarchive-dev \
            libcairo2-dev \
            libcurl4 \
            libcurl4-openssl-dev \
            libleptonica-dev \
            libpango1.0-dev

      - name: Setup Tesseract
        run: |
          ./autogen.sh
          echo $PWD
          ls -l .

      - name: Configure Tesseract
        run: |
          mkdir -p bin/release
          cd bin/release
          ../../configure \
            --disable-debug \
            --disable-doc \
            --disable-graphics \
            --disable-shared \
            --enable-openmp \
            'CXX=g++' \
            'CXXFLAGS=-g -O2 -fno-math-errno -Wall -Wextra -Wpedantic'
          echo $PWD
          ls -l .
    
      - name: Make Tesseract
        run: |
          cd bin/release
          make
          ls -l .

      - name: Make Training
        run: |
          cd bin/release
          make training
          ls -l .
